name: run-query-parse-test-suite
run-name: Running test suite
on: [push]
jobs:
  node-express:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - working-directory: node-express
    - run: npm install
    - run: node index.js &
    - uses: ./.github/actions/test.yaml
  render-test-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: ./node_modules/.bin/mustache sample.json templates/index.mustache
