name: run-query-parse-test-suite
run-name: Running test suite
on: [push]
permissions:
  contents: write
jobs:
  node-express:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frameworks/node-express
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: ./setup
    - run: ./serve
    - id: run-tests
      working-directory: .
      run: ./bin/run > results.json
    - name: Save node-express results
      uses: actions/upload-artifact@v3
      with:
        name: node-express-results
        path: results.json
  php-vanilla:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frameworks/php-vanilla
    steps:
    - uses: actions/checkout@v3
    - run: ./serve
    - id: run-tests
      working-directory: .
      run: ./bin/run > results.json
    - name: Save php-vanilla results
      uses: actions/upload-artifact@v3
      with:
        name: php-vanilla-results
        path: results.json
  python-django:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frameworks/python-django
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
         python-version: 3.8
    - run: ./setup
    - run: ./serve
    - id: run-tests
      working-directory: .
      run: ./bin/run > results.json
    - name: Save python-django results
      uses: actions/upload-artifact@v3
      with:
        name: python-django-results
        path: results.json
  ruby-on-rails:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frameworks/ruby-on-rails
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1.152.0
      with:
        ruby-version: '3.1'
    - run: ./setup
    - run: ./serve
    - id: run-tests
      working-directory: .
      run: ./bin/run > results.json
    - name: Save ruby-on-rails results
      uses: actions/upload-artifact@v3
      with:
        name: ruby-on-rails-results
        path: results.json
  publish:
    runs-on: ubuntu-latest
    needs:
    - node-express
    - php-vanilla
    - python-django
    - ruby-on-rails
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - run: ./bin/render
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        folder: publish

